<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1LMQCQQ" failures="1" tests="5" name="listnersnew.TestClass" time="0.041" errors="0" timestamp="2022-08-03T23:12:43 IST" skipped="2">
  <testcase classname="listnersnew.TestClass" name="method4" time="0.000">
    <skipped/>
  </testcase> <!-- method4 -->
  <system-out>
    <![CDATA[TestCase has been Skipped
TestCase has been Started]]>
  </system-out>
  <testcase classname="listnersnew.TestClass" name="method3" time="0.009">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listnersnew.TestClass.method3(TestClass.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- method3 -->
  <system-out>
    <![CDATA[TestCase has been Started
TestCase has been Failed]]>
  </system-out>
  <testcase classname="listnersnew.TestClass" name="method5" time="0.000">
    <skipped/>
  </testcase> <!-- method5 -->
  <system-out>
    <![CDATA[TestCase has been Skipped]]>
  </system-out>
  <testcase classname="listnersnew.TestClass" name="method2" time="0.006"/>
  <system-out>
    <![CDATA[TestCase has been Started
method2 exicuted succesfull
TestCase has been Passed]]>
  </system-out>
  <testcase classname="listnersnew.TestClass" name="method1" time="0.026"/>
  <system-out>
    <![CDATA[TestCase has been Started
method1 exicuted succesfull
TestCase has been Passed]]>
  </system-out>
</testsuite> <!-- listnersnew.TestClass -->
